### ISSUE TITLE
video playback shot in portrait mode should 'fit to screen" in portrait mode while maintaining original size ratio

### ISSUE THREAD

**Issue by truckerboy** [Piwigo/piwigo-flutter-app#130]
Video playback should 'fit to screen" in landscape and portrait mode while maintaining original size ratio. Setting the ability to scale to fit screen as an option would be ideal.
In current state some videos are way too small and barely visible in original size.

**Comment by remi-martin** [comment]
hi, this should have been fixed, what version of Piwigo NG are you using ?

I'll still try to reproduce it on my side.

**Comment by truckerboy** [comment]
The issue is indeed fixed for videos taken in landscape mode. 
The issue remains for videos taken in portrait mode. Portrait mode videos stay in miniature size when phone is held in portrait mode. However when phone is rotated to landscape mode, it correctly fits the screen. 
So the issue only exists for portrait mode videos when phone is held in portrait mode. Correct behavior would be for video to stretch and fill the screen when portrait mode video is viewed in portrait mode.

**Comment by remi-martin** [comment]
hmmm, I have changed what, for me, could cause this issue. I have tried the solution with different video sizes and format ratio and it always fits ether height or width of the screen.

The patch should be rolling this week, I'll let you know when it's available so you can see if you still have the issue.

**Comment by truckerboy** [comment]
not fixed in 1.2.0. unchanged from Google Play version.

**Comment by remi-martin** [comment]
Alright, I'll get over it later for more testing

**Comment by truckerboy** [comment]
This issue can be closed. I am quite sure the fix was released several versions ago but as of Piwigo NG version 2.2.3, I can report the issue no longer exists.
